[package]
name = "bevy_simple_2d_outline"
version = "0.1.0"
edition = "2021"
description = "A simple 2d outline shader for Bevy"
categories = ["graphics","rendering"]
license = "MIT OR Apache-2.0"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.9.0", default-features = false, features = [
    "bevy_asset",
    "render",
    "png",
    "tga",
] }

[dev-dependencies]
bevy = { version = "0.9.0", features = ["tga"] }